[project]
name = "dimensionador-solar"
version = "0.1.0"
description = ""
authors = [
    {name = "Federico Da Silva",email = "fededamel@fiuna.edu.py"}
]
requires-python = ">=3.11"
dependencies = [
    "yes (>=0.0.1,<0.0.2)",
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.53.0,<0.54.0)",
    "sqlalchemy (>=2.0.54,<3.0.0)",
    "aiosqlite (>=0.22.1,<0.23.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "beautifulsoup4 (>=4.15.0,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
